### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [chantelwetzel-noaa/copper_rockfish_2021#1]
https://github.com/chantelwetzel-noaa/copper_rockfish_2021/blob/91d2f3880a986356f656b8c74505f5f10377381c/write_up/wa/22biology.Rmd#L7

this didn't work on my machine b/c i have a different base directory. we should think about the costs and benefits of using the following:
1. relative paths
2. full paths
3. created paths via R variables

I was able to use ../general_text/data_m.Rmd

**Comment by chantelwetzel-noaa** [comment]
Agreed. I had actually updated this approach this morning to use option #3.  I anticipate creating R variables for things like the general text, but also for places for external tables or figures created outside of r4ss.
